function make_gp_plot(x, mean, variance, train_x, train_y, bounds, ...
                      dot_size, x_label, train_label, legend_location, ...
                      width, height)

  x = x(:);

  mean = mean(:);
  mean(isnan(mean)) = 0;

  stds = sqrt(variance(:));
  stds(isnan(stds)) = 0;
  stds(stds == 0) = eps;
  
  fh = figure;

  hold off;
  SDh = fill([x; x(end:-1:1)], ...
             [mean + 2 * stds; mean(end:-1:1) - 2 * stds(end:-1:1)], ...
             [0.87 0.89 1], 'EdgeColor', 'none');
  hold on;
  observationsh = plot(train_x, train_y, '.');
  meanh = plot(x, mean);
  
  position = get(fh, 'position'); 
  set(fh, ...
      'color', 'white', ...
      'units', 'centimeters', ... 
      'numbertitle', 'off', ...
      'position', [position(1:2), width, height] ...
      );
  
  axis(bounds);
  
  set(gca, ...
      'tickdir', 'out', ...
      'box', 'off', ...
      'fontsize', 10 ...
      );
  
  set(meanh, ... 
      'linestyle', '-', ...
      'linewidth', 2, ...
      'color', [0 0 0.8] ...
      );
  
  set(meanh, ... 
      'linestyle', '-', ...
      'linewidth', 1, ...
      'color', [0 0 0.8] ...
      );
  
  set(observationsh, ... 
      'lineStyle', 'none', ...
      'marker', '.', ...
      'markersize', dot_size, ...
      'color', [0.25 0.25 0.25] ...
      );
  
  xlabel(x_label);
  
  legend( ...
      [observationsh, meanh, SDh], ...
      train_label, ...
      'mean' , ...
      '+/- 2 SD', ...
      'Location', ...
      legend_location ...
      );
  legend('boxoff');

  drawnow;
end